-- Create the shopping_list_items table to store items users plan to buy
create table public.shopping_list_items (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone not null default now(),
  product_name text not null,
  vendor_name text,
  price numeric not null,
  quantity integer not null default 1,
  image_url text
);

-- Enable Row Level Security for the new table
alter table public.shopping_list_items enable row level security;

-- Add policies to ensure users can only access their own shopping list items
create policy "Users can view their own shopping list items."
  on public.shopping_list_items for select
  using (auth.uid() = user_id);

create policy "Users can insert their own shopping list items."
  on public.shopping_list_items for insert
  with check (auth.uid() = user_id);

create policy "Users can delete their own shopping list items."
  on public.shopping_list_items for delete
  using (auth.uid() = user_id);
